---
- name: Stop and uninstall Nginx on Ubuntu and Amazon Linux
  hosts: all
  become: yes

  tasks:

    - name: Stop and disable Nginx service
      service:
        name: nginx
        state: stopped
        enabled: no

    - name: Uninstall Nginx on Debian/Ubuntu
      apt:
        name: nginx
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Uninstall Nginx on Amazon Linux / RedHat
      yum:
        name: nginx
        state: absent
      when: ansible_os_family == "RedHat"
