---
- name: Install Nginx on Ubuntu and Amazon Linux
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache (for Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update yum cache (for Amazon Linux)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install nginx on Ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install nginx on Amazon Linux
      yum:
        name: nginx
        state: present
